# Generated by Django 4.2.27 on 2026-06-21 10:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(default=datetime.date.today)),
                ("target_minutes", models.PositiveIntegerField(default=0)),
                ("achieved_minutes", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Goal",
                "verbose_name_plural": "Daily Goals",
                "ordering": ["-date"],
            },
        ),
        migrations.AddConstraint(
            model_name="dailygoal",
            constraint=models.UniqueConstraint(
                fields=("user", "date"), name="unique_user_date_goal"
            ),
        ),
    ]
